
proxies:
  - name: MySOCKS5Proxy
    type: socks5
    server: 160.250.167.33
    port: 45270
    username: taikhoangem176
    password: '0938003636'

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - MySOCKS5Proxy

rules:
  - MATCH,Proxy
